#!/bin/bash

username=replaceme
pass=replaceme

print_help() {
    echo "Usage: $0 <FIXTURE-ID> <command> [filename]"
    echo
    echo "<FIXTURE-ID> - The fixture ID of the station, e.g. DFXM-EDGE-AWESOME01."
    echo "<command>  - Can be either 'ls' or 'get'."
    echo "[filename] - Optional file name. Required if the command is 'get'."
}

# Check if there are fewer than 2 arguments
if [ "$#" -lt 2 ]; then
    print_help
    exit 1
fi

# Assigning the input arguments to variables
# awk '/ipv4_primary/ { match($0, /([0-9]{1,3}\.){3}[0-9]{1,3}/, arr); print arr[0] }' filename.txt

fixture_id="$1"
hostname=$(mender -n $fixture_id -m info | awk '/ipv4_primary/ { split($3, arr, "/"); print arr[1] }')
command="$2"
filename="$3"

case $command in
    "ls")
        sshpass -p $pass ssh $username@$hostname ls -l /var/log/syslog*
        ;;
    "get")
        if [ -z "$filename" ]; then
            echo "Error: filename is required for the 'get' command."
            exit 1
        fi
        sshpass -p $pass scp $username@$hostname:/var/log/"$filename" ./
        ;;
    *)
        echo "Invalid command. It can be either 'ls' or 'get'."
        print_help
        exit 1
        ;;
esac


